baseURL = 'http://yugiohaccess.com'
title = 'YuGiOh Access'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

languageCode = 'en-us'
defaultContentLanguage = "en"
languageName = "English"
copyright = "&copy; YuGiOh Acces & contributors"
enableRobotsTXT = true
enableEmoji = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Discord"
url = "https://discord.gg/PhQkxXkR5d"
weight = 2

[[menu.main]]
name = "GitHub"
url = "https://github.com/YuGiOhAccess"
weight = 3
